name: flutter_projects
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0 
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.7
  dio: ^4.0.1
  pin_code_text_field: ^1.8.0
  pin_code_fields: ^7.4.0
  crypto: ^3.0.2
  flutter_spinkit: ^5.1.0
  convex_bottom_bar: ^3.0.0
  dotted_line: ^3.1.0
  smooth_star_rating_null_safety: ^1.0.4+2
  otp_text_field: ^1.1.3
  sidebarx: ^0.12.0
  flutter_svg: ^1.1.5
  im_stepper: ^1.0.1+1
  cached_network_image: any
  dots_indicator: ^2.1.0
  page_view_indicators: ^2.0.0
  image_picker: ^0.8.5+3
  image_cropper: ^1.4.1
  permission_handler: ^10.0.1
  mime_type: ^1.0.0
  http_parser: ^4.0.2
  dropdown_search: ^5.0.3
  flutter_colorpicker: ^1.0.3
  dotted_border: ^2.0.0+2
  fluttertoast: ^8.1.1
  autocomplete_textfield: ^2.0.1
  dropdown_textfield: ^1.0.6
  input_history_text_field: ^0.2.0
  badges: ^2.0.3
  textfield_search: ^0.10.0
  syncfusion_flutter_charts: ^20.3.58
  flutter_switch: ^0.3.2
  google_sign_in: ^5.4.2
  flutter_plugin_android_lifecycle: ^2.0.19
  photo_view: ^0.14.0
  expandable_text: ^2.3.0
  cloud_firestore: ^4.2.0  # Specifying version 4.2.0 of cloud_firestore
  firebase_crashlytics: ^3.0.7
  firebase_core: ^2.24.0
  firebase_auth: ^4.2.1
  firebase_analytics: ^10.0.7
  uuid: ^4.1.0
  flutter_launcher_icons: ^0.13.1
  carousel_slider: ^4.2.1
  firebase_storage: ^11.5.3
  firebase_messaging: ^14.7.6
  flutter_local_notifications: ^12.0.4
  url_launcher: ^6.2.2
  maps_launcher: ^2.2.0
  flutter_lints: ^2.0.3
  geocoding: ^2.1.1
  geodesy: ^0.10.2
  firebase_remote_config: ^4.3.8
  firebase_database: ^10.5.6
  rxdart: ^0.27.2
  google_maps_flutter: ^2.6.1 # Add Google Maps Flutter package
   # Add flutter_leaflet package version 0.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
    

flutter:
  uses-material-design: true
  assets:
    - assets/homepage1.jpeg
    - assets/account.jpg
    - assets/rolepage.jpg
